version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "19090:9090"
    volumes:
      - ./2.prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    ports:
      - "0.0.0.0:13000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana_dashboard.json:/var/lib/grafana/dashboards/grafana_dashboard.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
